config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :pages

  get "room-list" => "pages#list"
  get "room-grid" => "pages#grid"
  get "room-single-page" => "pages#single_page"
  get  "about-us" => "pages#about"
  get "contact-us"=> "pages#contact"
  get "review-page" => "pages#review"
  get "spa" => "pages#spa"
  get "wedding-page" => "pages#wedding"
  get "coming-soon" => "pages#coming"
  get "error"=> "pages#error"
  get "dining-menu" => "pages#dining"
  get "gallery" => "pages#gallery"
  get "blog-page"=> "pages#blog"
  get "single-post" => "pages#single_post"
  get "event-list" => "pages#event_list"
  get "events" => "pages#events"


  

  root "pages#index"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def index 

	end 

	def show
		session[:page] = params[:id]
		redirect_to root_url 
	end

	def list

	end

	def grid

	end 

	def single_page 

	end 

	def about

	end 

	def contact

	end 

	def review

	end

	def spa

	end

	def wedding

	end

	def coming

	end

	def error

	end

	def dining

	end 

	def gallery

	end

	def blog

	end

	def single_post

	end 

	def event_list

	end 

	def events

	end

	def room_single

	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application'%>
    <%= javascript_include_tag 'application' %>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyA3SxFkcHa9sTHRJHoAD7TlU23URYL6vfs&amp;#038;ver=4.7.2">      </script>
  </head>

  <body>
    <%= render "shared/header"%>
    <%= yield %>
    <%= render "shared/footer"%>

  </body>
</html>

app/views/pages/coming.html.erb
 <!--================= Content Area ===================-->
    <div data-jarallax="{&quot;speed&quot;: 0.3, &quot;imgSrc&quot;: &quot;/assets/error-bg.jpg&quot; }" class="coming-soon-page jarallax">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <div class="section-title-area text-center">
              <h2 class="section-title">Coming Soon</h2>
              <p class="section-title-dec">We are working on something awesome!</p>
            </div><!--/.section-title-area-->
          </div><!--/.col-md-12-->
        </div><!--/.row-->
        <div class="row">
          <div class="col-md-7 col-full-width">
            <div class="timer-content-area text-center">
              <div id="countdown"></div>
              <div class="social-share"><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a><a href="#"><i class="fa fa-google-plus"></i></a></div><!--/.social-share-->
            </div><!--/.timer-content-area-->
          </div><!--/.col-md-7-->
        </div><!--/.row-->
      </div><!--/.container-->
    </div><!--/.coming-soon-page-->
    <!--================= Site Footer ===================-->

app/views/pages/grid.html.erb
<!--================= Page Wellcome Area ===================-->
    <div class="page-heading-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h2 class="page-heading">find your room
            </h2><!--/.page-heading-->
          </div><!--/.col-md-12-->
        </div><!--/.row-->
      </div><!--/.container--> 
    </div><!--/.page-heading-area-->
    <div class="page-nav-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb page-nav list-unstyled">
              <li><a href="<%= root_url %>">Home</a></li>
              <li>Room
              </li>
            </ul><!--/.page-nav-->
          </div><!--/.col-md-12-->
        </div><!--/.row-->
      </div><!--/.container-->
    </div><!--/.page-title-area-->
    <!--================= Content Area ===================-->
    <div class="room-grid-area">
      <div class="container">
        <div class="row">
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-1.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-2.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5><a href="<%= room_single_page_url %>" class="room-title"></a>
                <h3 class="room-title"><a href="#">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-3.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="clearfix hidden-xs"></div>
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-4.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-5.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-6.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="clearfix hidden-xs"></div>
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-5.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-2.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
          <div class="col-md-4 col-sm-6 col-xs-6">
            <div class="single-room grid"><img src="/assets/rooms/img-4.jpg" alt="room" class="room-thumb">
              <div class="room-info box-radius">
                <h5>Starting from $50 / Night </h5>
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h4 class="room-structure">02 King Bed / Max 4 Peoples  </h4>
                <div class="room-services">                           <i class="fa fa-eye"></i><i class="fa fa-television"></i><i class="fa fa-microphone-slash"></i><i class="fa fa-coffee"></i><i class="fa fa-cutlery"></i><i class="fa fa-wifi"></i></div><a href="<%= room_single_page_url %>" class="btn btn-details">more details</a>
              </div>
            </div><!--/.single-room-->
          </div><!--/.col-md-4-->
        </div><!--/.row-->
        <div class="row">
          <div class="col-md-12">
            <!--Paginations-->
            <nav class="paginations">
              <div class="post-pagination paging-navigation">
                <ul class="nav-links">
                  <li class="nav-previous">
                    <!--disabled add when no pagination--><a href="#"><i class="fa fa-angle-left"></i></a>
                  </li>
                  <li><a href="#">01</a></li>
                  <li class="active"><a href="#">02</a></li>
                  <li><a href="#">03</a></li>
                  <li><a href="#">04</a></li>
                  <li><a href="#">...</a></li>
                  <li><a href="#">102</a></li>
                  <li class="nav-next"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                </ul>
              </div><!--/.post-pagination-->
            </nav><!--/.pagination-->
          </div><!--/.col-md-12-->
        </div><!--/.row-->
      </div><!--/.container-->
    </div><!--/.room-grid-area-->
    <!--================= Site Footer ===================-->

app/views/pages/index.html.erb
<% if session[:page] and session[:page] == "2" %>
<%= render "index2"%>

<% else %>
<%= render "index1"%>
<% end %>
  

app/views/pages/list.html.erb
 <div class="page-heading-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12 text-center">
            <h2 class="page-heading">find your room
            </h2><!--/.page-heading-->
          </div><!--/.col-md-12-->
        </div><!--/.row-->
      </div><!--/.container--> 
    </div><!--/.page-heading-area-->
    <div class="page-nav-area">
      <div class="container">
        <div class="row">
          <div class="col-md-12">
            <ul class="breadcrumb page-nav list-unstyled">
              <li><a href="<%= root_url %>">Home</a></li>
              <li>List
              </li>
            </ul><!--/.page-nav-->
          </div><!--/.col-md-12-->
        </div><!--/.row-->
      </div><!--/.container-->
    </div><!--/.page-title-area-->
    <!--================= Content Area ===================-->
    <div class="room-list-area">
      <div class="container">
        <!--Single Room-->
        <div class="single-room list">
          <div class="row">
            <div class="col-md-5 padding-right">
              <figure class="room-thumb"><img src="/assets/rooms/list/room-1.jpg" alt="img" class="box-radius"></figure><a href="<%= room_single_page_url %>" class="btn btn-details">View Details Information And Book<i class="fa fa-arrow-right"></i></a>
            </div><!--/.col-md-5-->
            <div class="col-md-7">
              <div class="room-info">
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h5>Starting from $50 / Night</h5>
                <h4 class="room-structure">2 King Bed / Max 6 people included / 1 Full Sofa set.</h4>
                <ul class="room-services list-unstyled">
                  <li><i class="fa fa-home"></i>Room Size 350 FT<sup>2</sup></li>
                  <li><i class="fa fa-laptop"></i>computer</li>
                  <li><i class="fa fa-eye"></i>Awesome View</li>
                  <li><i class="fa fa-wifi"></i>WIFI</li>
                  <li><i class="fa fa-television"></i>Flat Screen TV</li>
                  <li><i class="fa fa-microphone-slash"></i>Air Condition</li>
                  <li><i class="fa fa-eye"></i>Soundproof</li>
                  <li><i class="fa fa-coffee"></i>Breakfast Included</li>
                  <li><i class="fa fa-microphone-slash"></i>Room Service</li>
                  <li><i class="fa fa-plane"></i>Airport Pickup</li>
                </ul>
              </div><!--/.room-info-->
            </div><!--/.col-md-7-->
          </div><!--/.row-->
        </div><!--/.single-room-->
        <!--Single Room-->
        <div class="single-room list">
          <div class="row">
            <div class="col-md-5 padding-right">
              <figure class="room-thumb"><img src="/assets/rooms/list/room-2.jpg" alt="img" class="box-radius"></figure><a href="<%= room_single_page_url %>" class="btn btn-details">View Details Information And Book<i class="fa fa-arrow-right"></i></a>
            </div><!--/.col-md-5-->
            <div class="col-md-7">
              <div class="room-info">
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h5>Starting from $50 / Night</h5>
                <h4 class="room-structure">2 King Bed / Max 6 people included / 1 Full Sofa set.</h4>
                <ul class="room-services list-unstyled">
                  <li><i class="fa fa-home"></i>Room Size 350 FT<sup>2</sup></li>
                  <li><i class="fa fa-laptop"></i>computer</li>
                  <li><i class="fa fa-eye"></i>Awesome View</li>
                  <li><i class="fa fa-wifi"></i>WIFI</li>
                  <li><i class="fa fa-television"></i>Flat Screen TV</li>
                  <li><i class="fa fa-microphone-slash"></i>Air Condition</li>
                  <li><i class="fa fa-eye"></i>Soundproof</li>
                  <li><i class="fa fa-coffee"></i>Breakfast Included</li>
                  <li><i class="fa fa-microphone-slash"></i>Room Service</li>
                  <li><i class="fa fa-plane"></i>Airport Pickup</li>
                </ul>
              </div><!--/.room-info-->
            </div><!--/.col-md-7-->
          </div><!--/.row-->
        </div><!--/.single-room-->
        <!--Single Room-->
        <div class="single-room list">
          <div class="row">
            <div class="col-md-5 padding-right">
              <figure class="room-thumb"><img src="/assets/rooms/list/room-3.jpg" alt="img" class="box-radius"></figure><a href="<%= room_single_page_url %>" class="btn btn-details">View Details Information And Book<i class="fa fa-arrow-right"></i></a>
            </div><!--/.col-md-5-->
            <div class="col-md-7">
              <div class="room-info">
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h5>Starting from $50 / Night</h5>
                <h4 class="room-structure">2 King Bed / Max 6 people included / 1 Full Sofa set.</h4>
                <ul class="room-services list-unstyled">
                  <li><i class="fa fa-home"></i>Room Size 350 FT<sup>2</sup></li>
                  <li><i class="fa fa-laptop"></i>computer</li>
                  <li><i class="fa fa-eye"></i>Awesome View</li>
                  <li><i class="fa fa-wifi"></i>WIFI</li>
                  <li><i class="fa fa-television"></i>Flat Screen TV</li>
                  <li><i class="fa fa-microphone-slash"></i>Air Condition</li>
                  <li><i class="fa fa-eye"></i>Soundproof</li>
                  <li><i class="fa fa-coffee"></i>Breakfast Included</li>
                  <li><i class="fa fa-microphone-slash"></i>Room Service</li>
                  <li><i class="fa fa-plane"></i>Airport Pickup</li>
                </ul>
              </div><!--/.room-info-->
            </div><!--/.col-md-7-->
          </div><!--/.row-->
        </div><!--/.single-room-->
        <!--Single Room-->
        <div class="single-room list">
          <div class="row">
            <div class="col-md-5 padding-right">
              <figure class="room-thumb"><img src="/assets/rooms/list/room-1.jpg" alt="img" class="box-radius"></figure><a href="<%= room_single_page_url %>" class="btn btn-details">View Details Information And Book<i class="fa fa-arrow-right"></i></a>
            </div><!--/.col-md-5-->
            <div class="col-md-7">
              <div class="room-info">
                <h3 class="room-title"><a href="<%= room_single_page_url %>">Room With ExtraFields</a></h3>
                <h5>Starting from $50 / Night</h5>
                <h4 class="room-structure">2 King Bed / Max 6 people included / 1 Full Sofa set.</h4>
                <ul class="room-services list-unstyled">
                  <li><i class="fa fa-home"></i>Room Size 350 FT<sup>2</sup></li>
                  <li><i class="fa fa-laptop"></i>computer</li>
                  <li><i class="fa fa-eye"></i>Awesome View</li>
                  <li><i class="fa fa-wifi"></i>WIFI</li>
                  <li><i class="fa fa-television"></i>Flat Screen TV</li>
                  <li><i class="fa fa-microphone-slash"></i>Air Condition</li>
                  <li><i class="fa fa-eye"></i>Soundproof</li>
                  <li><i class="fa fa-coffee"></i>Breakfast Included</li>
                  <li><i class="fa fa-microphone-slash"></i>Room Service</li>
                  <li><i class="fa fa-plane"></i>Airport Pickup</li>
                </ul>
              </div><!--/.room-info-->
            </div><!--/.col-md-7-->
          </div><!--/.row-->
        </div><!--/.single-room-->
        <div class="row">
          <div class="col-md-12">
            <!--Paginations-->
            <nav class="paginations">
              <div class="post-pagination paging-navigation">
                <ul class="nav-links">
                  <li class="nav-previous">
                    <!--disabled add when no pagination--><a href="#"><i class="fa fa-angle-left"></i></a>
                  </li>
                  <li><a href="#">01</a></li>
                  <li class="active"><a href="#">02</a></li>
                  <li><a href="#">03</a></li>
                  <li><a href="#">04</a></li>
                  <li><a href="#">...</a></li>
                  <li><a href="#">102</a></li>
                  <li class="nav-next"><a href="#"><i class="fa fa-angle-right"></i></a></li>
                </ul>
              </div><!--/.post-pagination-->
            </nav><!--/.pagination-->
          </div><!--/.col-md-12-->
        </div><!--/.row-->
      </div><!--/.container-->
    </div><!--/.room-list-area-->

app/views/shared/_header.html.erb
 <header id="masthead" class="site-header">
 	<div class="header-top">
 		<div class="container">
 			<div class="row">
 				<div class="col-md-8 hidden-xs">
 					<div class="addresses">
 						<div class="block-time"><i class="fa fa-clock-o"></i>
 							<p>Book Time - <span>10am to 11pm</span></p>
 						</div>
 						<div class="phone"><i class="fa fa-phone"></i>
 							<p>Call Us - <span>xxxxxxxxxxxxx</span></p>
 						</div>
 						<div class="email"><i class="fa fa-envelope"></i>
 							<p>mail@zzz.com</p>
 						</div>
 					</div><!--/.addresses-->
 				</div><!--/.col-md-8-->
 				<div class="col-md-4">
 					<div class="social-links"><a href="#"><i class="fa fa-instagram"></i></a><a href="#"><i class="fa fa-google-plus"></i></a><a href="#"><i class="fa fa-facebook"></i></a><a href="#"><i class="fa fa-twitter"></i></a></div><!--/.social-links-->
 					<div class="search-area hidden-xs"><i class="fa fa-search"></i>
 						<div class="header-search">
 							<div class="search default">
 								<form action="#" method="get" class="searchform">
 									<div class="input-group">
 										<input type="search" name="s" placeholder="Search here..." class="form-controller"><span class="input-group-btn">
 											<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button></span>
 										</div>
 									</form>
 								</div>
 							</div>
 						</div>
 						<div class="mobile-search-area hidden-sm hidden-md hidden-lg">
 							<!--i.fa.fa-search-->
 							<div class="header-search">
 								<div class="search default">
 									<form action="#" method="get" class="searchform">
 										<div class="input-group">
 											<input type="search" name="s" placeholder="Search here..." class="form-controller"><span class="input-group-btn">
 												<button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button></span>
 											</div>
 										</form>
 									</div>
 								</div>
 							</div><!--/.search-area-->
 						</div><!--/.col-md-4-->
 					</div><!--/.row-->
 				</div><!--/.container-->
 			</div><!--/.header-top-->
 			<!--Header Bottom-->
 			<div class="header-bottom">
 				<div class="container">
 					<div class="row">
 						<div class="col-md-12">
 							<div class="menu-wrapper clearfix">
 								<div class="navbar-header pull-left">
 									<div class="logo-block"><a href="index.html" class="site-logo"><p alt="sitelogo" class="logo">Logo Here</p></a><!--/.site-logo--></div>
 								</div><!--/.navbar-header-->
 								<div class="collapse navbar-collapse pull-right">
 									<div class="navigation hidden-sm hidden-xs">
 										<ul class="nav navbar-nav mainmenu">
 											<li><a href="#">Home</a>
 												<ul class="sub-menu">
 													<li><a href="<%= page_url(id: 1)%>">Home One</a></li>
 													<li><a href="<%= page_url(id: 2)%>">Home Two</a></li>
 												</ul>
 											</li>
 											<li><a href="#">Rooms</a>
 												<ul class="sub-menu">
 													<li><a href="<%= room_list_url %>">Room List</a></li>
 													<li><a href="<%= room_grid_url %>">Room Grid        </a></li>
 													<li><a href="<%= room_single_page_url %>">Room Single Page</a></li>
 												</ul>
 											</li>
 											<li><a href="#">Pages</a>
 												<ul class="sub-menu">
 													<li><a href="<%= about_us_url %>">About Page</a></li>
 													<li><a href="<%= contact_us_url%>">Contact Page</a></li>
 													<li><a href="<%= review_page_url %>">Review Page</a></li>
 													<li><a href="<%= spa_url %>">Spa Page</a></li>
 													<li><a href="<%= wedding_page_url %>">Wedding Page            </a></li>
 													<li><a href="<%= coming_soon_url %>">Coming Soon Page            </a></li>
 													<li><a href="<%= error_url %>">404 Page</a></li>
 												</ul>
 											</li>
 											<li><a href="<%= dining_menu_url%>">Dining</a></li>
 											<li><a href="<%= gallery_url%>">Gallery</a></li>
 											<li><a href="#">Blog</a>
 												<ul class="sub-menu">
 													<li><a href="<%= blog_page_url %>">Blog                               </a></li>
 													<li><a href="<%= single_post_url %>">Blog Single</a></li>
 												</ul>
 											</li>
 											<li><a href="#">Events</a>
 												<ul class="sub-menu">
 													<li><a href="<%= event_list_url  %>">Event List                               </a></li>
 													<li><a href="<%= events_url %>">Event Time-line</a></li>
 												</ul>
 											</li>
 										</ul><!--/.mainmenu-->
 									</div><!--/.navigation-->
 									<!--Mobile Main Menu-->
 									<div class="mobile-menu-main hidden-md hidden-lg">
 										<div class="menucontent overlaybg"> </div>
 										<div class="menuexpandermain slideRight"><a id="navtoggole-main" class="animated-arrow slideLeft menuclose"><span></span></a><span id="menu-marker"></span></div><!--/.menuexpandermain-->
 										<div id="mobile-main-nav" class="main-navigation slideLeft">
 											<div class="menu-wrapper">
 												<div id="main-mobile-container" class="menu-content clearfix"></div>
 											</div>
 										</div><!--/#mobile-main-nav-->
 									</div><!--/.mobile-menu-main-->
 								</div><!--/.navbar-collapse-->
 							</div><!--/.menu-wrapper-->
 						</div><!--/.col-md-12-->
 					</div><!--/.row-->
 				</div><!--/.container-->
 			</div><!--/.header-bottom-->
 		</header>